//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoAn1
{
    using System;
    using System.Collections.Generic;
    
    public partial class ThoiKhoaBieu
    {
        public int MaPH { get; set; }
        public int MaMH { get; set; }
        public int MaLop { get; set; }
        public int MaGV { get; set; }
        public int MaTiet { get; set; }
    
        public virtual GiaoVien GiaoVien { get; set; }
        public virtual Lop Lop { get; set; }
        public virtual MonHoc MonHoc { get; set; }
        public virtual PhongHoc PhongHoc { get; set; }
        public virtual Tiet Tiet { get; set; }
    }
}
